# Generated by Django 5.1.1 on 2024-11-21 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('photography', '0008_alter_photographytag_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.collection'),
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photography'),
        ),
    ]
