# Generated by Django 5.1.1 on 2024-11-11 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_collection_collectionphotography'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionphotography',
            unique_together={('collection', 'photography', 'user')},
        ),
    ]
