# Generated by Django 5.1.1 on 2024-11-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_alter_collectionphotography_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExifData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, max_length=255, null=True)),
                ('lens', models.CharField(blank=True, max_length=255, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('shutter_speed', models.FloatField(blank=True, null=True)),
                ('aperture', models.FloatField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('photography', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exif_data', to='photography.photography')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.photography')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.tag')),
            ],
        ),
    ]
