# Generated by Django 5.1.1 on 2024-11-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_tag_exifdata_photographytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.collection')),
            ],
        ),
    ]
