# Generated by Django 5.1.1 on 2024-11-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_alter_photographytag_photography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographytag',
            name='photography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photography_tags', to='photography.photography'),
        ),
    ]
