# Generated by Django 5.1.1 on 2024-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0008_alter_photographytag_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
