# Generated by Django 5.1.1 on 2024-11-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0009_collection_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='is_public',
            new_name='is_public_collection',
        ),
    ]
