# Generated by Django 5.1.1 on 2024-11-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0010_rename_is_public_collection_is_public_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='is_public_collection',
            new_name='is_public',
        ),
    ]
