# Generated by Django 5.1.1 on 2024-11-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0011_rename_is_public_collection_collection_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
