# Generated by Django 5.1.1 on 2024-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
