# Generated by Django 5.1.1 on 2024-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0002_statistics_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='visits_count',
            new_name='collections_views_count',
        ),
        migrations.AddField(
            model_name='statistics',
            name='photos_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
