# Generated by Django 5.1.1 on 2024-10-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='collections',
        ),
    ]
