# Generated by Django 5.1.1 on 2024-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_remove_portafolio_collections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portafoliocollection',
            unique_together=set(),
        ),
    ]
