# Generated by Django 5.1.1 on 2024-11-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('photography', '0008_alter_photographytag_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='photography.collection'),
        ),
        migrations.AddField(
            model_name='notification',
            name='photography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='photography.photography'),
        ),
    ]
