# Generated by Django 5.1.1 on 2024-11-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0008_alter_photographytag_photography'),
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.collection'),
        ),
        migrations.AddField(
            model_name='view',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photography'),
        ),
    ]
